org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.caching=true
version_forge=1.20.1
version_neoforge=1.21.1
mod_id=create_vvvf_simulator
mod_name=Create VVVF Simulator
mod_license=GPL-3.0
mod_version=2.0.0
mod_group_id=createvvvfsim
mod_authors=Deiloproxide
mod_description=Simulates VVVF on Minecraft Create Train