modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://deiloproxide.cn"
logoFile="icon.png"
authors="${mod_authors}"
description="""${mod_description}"""
[[mixins]]
config="${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies."${mod_id}"]]
modId="sound_physics_remastered"
mandatory=false
versionRange="${spr_version_range}"
ordering="AFTER"
side="CLIENT"
[[dependencies."${mod_id}"]]
modId="sound_physics_perfected"
mandatory=false
versionRange="${spp_version_range}"
ordering="AFTER"
side="CLIENT"