package createvvvfsim;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.loading.FMLEnvironment;
import net.neoforged.neoforge.common.ModConfigSpec;
import net.neoforged.neoforge.common.ModConfigSpec.DoubleValue;
import net.neoforged.neoforge.common.ModConfigSpec.IntValue;
@Mod(Configs.mod_id)
public class CreateVVVFSim{
    public static final int mixin_priority=1027;
    public static final String mod_id="create_vvvf_simulator";
    public static final String sync_name="train_sync";
    public static final String sound_name="train_vvvf";
    public static final String version="1.0.0";
    public static final String command_vvvf="vvvf";
    public static final String command_reload="reload";
    public static final String command_return="§a[Create: VVVF-Simulator] Reloaded!§r";
    public static final String filter_wav="/assets/createvvvfsim/trainsound/Filter.wav";
    public static final String table="/assets/createvvvfsim/switchangle/";
    public static final ModConfigSpec server_config;
    public static final ModConfigSpec client_config;
    public static final IntValue sync_period;
    public static final IntValue eval_period;
    public static final IntValue sample_rate;
    public static final IntValue buffer_size;
    public static final IntValue conv_size;
    public static final IntValue table_size;
    public static final IntValue speeds_length;
    public static final DoubleValue max_acc_ratio;
    public static final DoubleValue main_amp;
    public static final DoubleValue gas_amp;
    public static final DoubleValue switch_amp;
    public static final DoubleValue base_amp;
    public static final DoubleValue brown_amp;
    public static final DoubleValue vvvf_amp;
    public static final DoubleValue bg_wind_amp;
    public static final DoubleValue main_wind_amp;
    public static final DoubleValue near_distance;
    public static final DoubleValue far_distance;
    public static final DoubleValue base_current_f;
    public static final DoubleValue brown_sigma;
    public static final DoubleValue brown_range;
    public static final DoubleValue dry_wet_ratio;
    public static final DoubleValue line_train_ratio;
    public static final DoubleValue pink_r0;
    public static final DoubleValue wind_base_amp;
    public static final DoubleValue wind_mod_f;
    public static final DoubleValue wind_mod_depth;
    public static final DoubleValue bg_shear_base;
    public static final DoubleValue bg_shear_range;
    public static final DoubleValue bg_shear_rate;
    public static final DoubleValue hp_cutoff;
    public static final DoubleValue main_cauchy_amp;
    public static final DoubleValue main_center_f;
    public static final DoubleValue main_cauchy_gamma;
    public static final DoubleValue main_mod_f;
    public static final DoubleValue main_mod_depth;
    static{
        ModConfigSpec.Builder server_builder=new ModConfigSpec.Builder();
        server_builder.push("network");
        sync_period=server_builder.defineInRange("sync_period",3,1,20);
        server_builder.pop();
        server_config=server_builder.build();
        ModConfigSpec.Builder client_builder=new ModConfigSpec.Builder();
        client_builder.push("environment");
        eval_period=client_builder.defineInRange("eval_period",3,1,20);
        client_builder.pop();
        client_builder.push("audio");
        sample_rate=client_builder.defineInRange("sample_rate",44100,8000,192000);
        buffer_size=client_builder.defineInRange("buffer_size",1<<12,1<<10,1<<16);
        conv_size=client_builder.defineInRange("conv_size",1<<10,1<<8,1<<12);
        table_size=client_builder.defineInRange("table_size",1<<17,1<<12,1<<20);
        client_builder.pop();
        client_builder.push("speed_smoother");
        speeds_length=client_builder.defineInRange("speeds_length",5,1,20);
        max_acc_ratio=client_builder.defineInRange("max_acc_ratio",1.05,1.0,1.2);
        client_builder.pop();
        client_builder.push("audio_volumes");
        main_amp=client_builder.defineInRange("main_amp",1.0,0.0,2.0);
        gas_amp=client_builder.defineInRange("gas_amp",0.6,0.0,2.0);
        switch_amp=client_builder.defineInRange("switch_amp",0.4,0.0,2.0);
        base_amp=client_builder.defineInRange("base_amp",0.06,0.0,0.2);
        brown_amp=client_builder.defineInRange("brown_amp",0.03,0.0,0.2);
        vvvf_amp=client_builder.defineInRange("vvvf_amp",0.5,0.0,2.0);
        bg_wind_amp=client_builder.defineInRange("bg_wind_amp",3.0,0.0,10.0);
        main_wind_amp=client_builder.defineInRange("main_wind_amp",0.15,0.0,1.0);
        client_builder.pop();
        client_builder.push("spread_distance");
        near_distance=client_builder.defineInRange("near_distance",32.0,0.0,256.0);
        far_distance=client_builder.defineInRange("far_distance",96.0,0.0,256.0);
        client_builder.pop();
        client_builder.push("advanced");
        client_builder.push("equipment_sound");
        base_current_f=client_builder.defineInRange("base_current_f",140.0,0.0,500.0);
        brown_sigma=client_builder.defineInRange("brown_sigma",0.05,0.0,0.2);
        brown_range=client_builder.defineInRange("brown_range",2.0,0.0,10.0);
        client_builder.pop();
        client_builder.push("vvvf_sound");
        dry_wet_ratio=client_builder.defineInRange("dry_wet_ratio",0.0,0.0,1.0);
        line_train_ratio=client_builder.defineInRange("line_train_ratio",0.0,0.0,1.0);
        client_builder.pop();
        client_builder.push("bg_wind_sound");
        pink_r0=client_builder.defineInRange("pink_r0",0.99,0.0,1.0);
        wind_base_amp=client_builder.defineInRange("wind_base_amp",0.3,0.0,2.0);
        wind_mod_f=client_builder.defineInRange("wind_mod_f",0.2,0.0,2.0);
        wind_mod_depth=client_builder.defineInRange("wind_mod_depth",0.4,0.0,2.0);
        bg_shear_base=client_builder.defineInRange("bg_shear_base",800.0,0.0,2000.0);
        bg_shear_range=client_builder.defineInRange("bg_shear_range",400.0,0.0,2000.0);
        bg_shear_rate=client_builder.defineInRange("bg_shear_rate",0.8,0.0,2.0);
        hp_cutoff=client_builder.defineInRange("hp_cutoff",250.0,0.0,2000.0);
        client_builder.pop();
        client_builder.push("main_wind_sound");
        main_cauchy_amp=client_builder.defineInRange("main_cauchy_amp",0.65,0.0,2.0);
        main_center_f=client_builder.defineInRange("main_center_f",700.0,0.0,2000.0);
        main_cauchy_gamma=client_builder.defineInRange("main_cauchy_gamma",0.05,0.0,0.2);
        main_mod_f=client_builder.defineInRange("main_mod_f",0.15,0.0,0.2);
        main_mod_depth=client_builder.defineInRange("main_mod_depth",0.3,0.0,2.0);
        client_builder.pop();
        client_builder.pop();
        client_config=client_builder.build();
    }
    public CreateVVVFSim(ModContainer container){
        container.registerConfig(ModConfig.Type.SERVER,server_config);
        container.registerConfig(ModConfig.Type.CLIENT,client_config);
        if(FMLEnvironment.dist==Dist.CLIENT) ClientEvents.registerScreen(container);
    }
}